import { ArrowLeft, Clock3, FileCode2, Laptop, Link2, MapPin, ShieldAlert, UserRound } from 'lucide-react'
import Link from 'next/link'

import { Badge, Card, CardContent, CardDescription, CardHeader, CardTitle, Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui'
import type { ViewerDetailData, ViewerSessionDetail } from '@/lib/dashboard/viewers'

export function ViewerDetailView({ data }: { data: ViewerDetailData }) {
  const { summary, viewer, sessions, activity, timeline } = data
  return <div className="mx-auto w-full max-w-6xl space-y-7 px-6 py-10 lg:px-10 lg:py-14">
    <Link href="/dashboard/viewers" className="inline-flex items-center gap-2 text-sm text-foreground-muted underline-offset-4 hover:text-foreground hover:underline"><ArrowLeft className="size-4" />Back to viewers</Link>
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="space-y-3"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline"><UserRound className="mr-1.5 size-3" />Anonymous viewer</Badge><Badge variant="secondary">Unverified</Badge></div><h1 className="font-heading text-3xl font-semibold tracking-tight sm:text-4xl">{summary.displayName}</h1><p className="text-sm text-foreground-muted">{summary.recipientLabel || 'Generic share'}{summary.company ? ` · ${summary.company}` : ''} · Unverified</p><p className="text-sm text-foreground-muted">First seen {formatDate(viewer.firstSeenAt)} · Last seen {formatDate(viewer.lastSeenAt)}</p></div><div className="rounded-lg border border-border bg-muted/30 px-4 py-3 text-right"><p className="font-mono text-lg font-semibold">{summary.visits} {summary.visits === 1 ? 'visit' : 'visits'}</p><p className="text-xs text-foreground-muted">intended recipient label only</p></div></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Clock3 className="size-4" />} label="Active time" value={formatDuration(summary.totalViewingSeconds)} /><Stat icon={<FileCode2 className="size-4" />} label="Files viewed" value={String(summary.filesViewed)} /><Stat icon={<MapPin className="size-4" />} label="Approx. location" value={summary.location || 'Not available'} /><Stat icon={<RotateBackIcon />} label="Viewer ID" value={`#${viewer.code}`} /></div>
    <div className="flex items-start gap-3 rounded-lg border border-border bg-muted/30 p-4 text-sm leading-6 text-foreground-muted"><ShieldAlert className="mt-0.5 size-4 shrink-0 text-primary" /><p>Recipient metadata is an intended-recipient label, not proof of who opened the URL. Any security language below is an inferred signal and may be wrong.</p></div>
    <Tabs defaultValue="overview">
      <TabsList className="flex h-auto w-full flex-wrap justify-start gap-1 rounded-lg p-1"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="sessions">Sessions</TabsTrigger><TabsTrigger value="activity">Repository activity</TabsTrigger><TabsTrigger value="timeline">Timeline</TabsTrigger><TabsTrigger value="location">Location</TabsTrigger><TabsTrigger value="device">Device</TabsTrigger><TabsTrigger value="security">Security</TabsTrigger></TabsList>
      <TabsContent value="overview"><OverviewTab sessions={sessions} /></TabsContent>
      <TabsContent value="sessions"><SessionsTab sessions={sessions} /></TabsContent>
      <TabsContent value="activity"><ActivityTab activity={activity} /></TabsContent>
      <TabsContent value="timeline"><TimelineTab timeline={timeline} /></TabsContent>
      <TabsContent value="location"><LocationTab sessions={sessions} /></TabsContent>
      <TabsContent value="device"><ContextTab title="Prompt-free browser and device context" icon={<Laptop className="size-4" />} values={sessions[0]?.device ?? {}} /></TabsContent>
      <TabsContent value="security"><SecurityTab sessions={sessions} /></TabsContent>
    </Tabs>
  </div>
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <Card><CardContent className="space-y-3 p-5"><div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-foreground-muted">{icon}{label}</div><p className="truncate font-heading text-xl font-semibold tracking-tight" title={value}>{value}</p></CardContent></Card> }
function OverviewTab({ sessions }: { sessions: ViewerSessionDetail[] }) { return <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><Card><CardHeader><CardTitle>Visits</CardTitle><CardDescription>Sessions are separated by share opens and protected server cookies.</CardDescription></CardHeader><CardContent><SessionsTab sessions={sessions} compact /></CardContent></Card><Card><CardHeader><CardTitle>Engagement pattern</CardTitle><CardDescription>Observed file navigation across this viewer’s sessions.</CardDescription></CardHeader><CardContent><div className="space-y-3">{sessions.flatMap((session) => session.files).slice(0, 12).map((path, index) => <div key={`${path}-${index}`} className="flex items-center gap-3 text-sm"><span className="w-6 font-mono text-xs text-foreground-muted">{String(index + 1).padStart(2, '0')}</span><FileCode2 className="size-3.5 text-primary" /><span className="truncate font-mono text-xs">{path}</span></div>)}{sessions.every((session) => session.files.length === 0) ? <Empty text="No file engagement has been recorded yet." /> : null}</div></CardContent></Card></div> }
function SessionsTab({ sessions, compact = false }: { sessions: ViewerSessionDetail[]; compact?: boolean }) { return <Card><CardHeader><CardTitle>Sessions</CardTitle><CardDescription>{sessions.length} recorded {sessions.length === 1 ? 'session' : 'sessions'}. Active time is estimated from foreground activity.</CardDescription></CardHeader><CardContent><div className="space-y-3">{sessions.slice(0, compact ? 4 : undefined).map((session) => <div key={session.id} className="rounded-lg border border-border p-4"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><p className="font-medium">{session.shareLabel} · <span className="font-mono text-xs">{session.repositoryName}</span></p><p className="mt-1 text-xs text-foreground-muted">{formatDate(session.firstSeenAt)} → {formatDate(session.lastSeenAt)}</p></div><Badge variant="outline">{formatDuration(session.activeSeconds)} active</Badge></div><div className="mt-3 grid gap-2 text-xs text-foreground-muted sm:grid-cols-2 lg:grid-cols-4"><span>First file: <span className="font-mono text-foreground">{session.firstFile || 'None'}</span></span><span>Last file: <span className="font-mono text-foreground">{session.lastFile || 'None'}</span></span><span>Ref: <span className="font-mono text-foreground">{session.ref}</span></span><span>Commit: <span className="font-mono text-foreground">{session.commitSha ? session.commitSha.slice(0, 12) : 'Not pinned'}</span></span></div></div>)}{sessions.length === 0 ? <Empty text="No sessions have been recorded yet." /> : null}</div></CardContent></Card> }
function ActivityTab({ activity }: { activity: ViewerDetailData['activity'] }) { return <Card><CardHeader><CardTitle>Repository activity</CardTitle><CardDescription>Semantic interactions only; raw keylogging is never collected.</CardDescription></CardHeader><CardContent><div className="divide-y divide-border rounded-lg border border-border">{activity.map((event) => <div key={event.id} className="flex flex-col gap-1 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{formatEvent(event.eventType)}</p><p className="font-mono text-xs text-foreground-muted">{event.path || 'Session activity'}</p></div><time className="text-xs text-foreground-muted">{formatTime(event.createdAt)}</time></div>)}{activity.length === 0 ? <Empty text="No repository activity recorded yet." /> : null}</div></CardContent></Card> }
function TimelineTab({ timeline }: { timeline: ViewerDetailData['timeline'] }) { return <Card><CardHeader><CardTitle>Activity timeline</CardTitle><CardDescription>Chronological events from confirmed sessions.</CardDescription></CardHeader><CardContent><div className="relative space-y-0 border-l border-border pl-6">{timeline.map((event) => <div key={event.id} className="relative pb-5 last:pb-0"><span className="absolute -left-[29px] top-1 flex size-4 items-center justify-center rounded-full border border-border bg-background"><span className="size-1.5 rounded-full bg-primary" /></span><p className="text-sm font-medium">{formatEvent(event.eventType)}</p><p className="mt-1 font-mono text-xs text-foreground-muted">{event.path || 'Repository session'}</p><time className="mt-1 block text-xs text-foreground-muted">{formatTime(event.occurredAt)}</time></div>)}{timeline.length === 0 ? <Empty text="No timeline events recorded yet." /> : null}</div></CardContent></Card> }
function LocationTab({ sessions }: { sessions: ViewerSessionDetail[] }) { const location = sessions[0]?.location; return <Card><CardHeader><CardTitle><MapPin className="mr-2 inline size-4" />Approximate location</CardTitle><CardDescription>Coarse provider-supplied labels only. RepoView does not store postal codes or coordinates.</CardDescription></CardHeader><CardContent><dl className="grid gap-5 sm:grid-cols-3">{Object.entries({ City: location?.city, Region: location?.region, Country: location?.country }).map(([label, value]) => <div key={label}><dt className="text-xs uppercase tracking-wide text-foreground-muted">{label}</dt><dd className="mt-1 text-sm">{value ?? 'Not available'}</dd></div>)}</dl></CardContent></Card> }
function ContextTab({ title, icon, values }: { title: string; icon: React.ReactNode; values: Record<string, string | number | boolean | null> }) { return <Card><CardHeader><CardTitle>{icon}<span className="ml-2">{title}</span></CardTitle><CardDescription>Only prompt-free browser/session context is shown.</CardDescription></CardHeader><CardContent><dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(values).map(([label, value]) => <div key={label}><dt className="text-xs uppercase tracking-wide text-foreground-muted">{label.replaceAll(/([A-Z])/g, ' $1')}</dt><dd className="mt-1 break-words text-sm">{value === null || value === undefined ? 'Not available' : String(value)}</dd></div>)}</dl></CardContent></Card> }
function SecurityTab({ sessions }: { sessions: ViewerSessionDetail[] }) { return <Card><CardHeader><CardTitle><ShieldAlert className="mr-2 inline size-4" />Security signals</CardTitle><CardDescription>Signals are inferred and may be incorrect. “Possible link forwarding” is not a claim of identity.</CardDescription></CardHeader><CardContent><div className="space-y-3">{sessions.map((session) => <div key={session.id} className="rounded-lg border border-border p-4"><p className="text-sm font-medium">{formatDate(session.firstSeenAt)}</p><pre className="mt-2 overflow-x-auto whitespace-pre-wrap font-mono text-xs text-foreground-muted">{formatSecurity(session.security)}</pre></div>)}{sessions.length === 0 ? <Empty text="No security signals recorded." /> : null}</div></CardContent></Card> }
function Empty({ text }: { text: string }) { return <p className="rounded-lg border border-dashed border-border px-4 py-8 text-center text-sm text-foreground-muted">{text}</p> }
function formatEvent(value: string) { return value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()) }
function formatDate(value: string) { return new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function formatTime(value: string) { return new Intl.DateTimeFormat('en', { timeStyle: 'medium' }).format(new Date(value)) }
function formatDuration(seconds: number) { if (seconds < 60) return `${seconds}s`; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ${seconds % 60}s`; return `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m` }
function formatSecurity(value: unknown) { if (!value || typeof value !== 'object') return 'No inferred signals recorded.'; const entries = Object.entries(value as Record<string, unknown>).filter(([, field]) => field !== null && field !== false && field !== undefined); return entries.length > 0 ? entries.map(([key, field]) => `${key}: ${String(field)}`).join('\n') : 'No meaningful security signals recorded.' }
function RotateBackIcon() { return <Link2 className="size-4" /> }
